server:
  port: 8084

spring:
  application:
    name: currency-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/currency_db}
    username: ${SPRING_DATASOURCE_USERNAME:gustavo}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
  cache:
    type: simple

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

bcb:
  base-url: ${BCB_BASE_URL:https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/odata}

resilience4j:
  circuitbreaker:
    instances:
      bcbService:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
