eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:minha_chave_secreta_muito_segura_e_longa_para_o_jwt_jlpg_motors}
  expiration: ${JWT_EXPIRATION:86400000}
