server:
  port: 8083

spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:postgresql://localhost:5433/customer_db
    username: gustavo
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/