ALTER TABLE products
ADD COLUMN name VARCHAR(100) NOT NULL,
ADD COLUMN mileage INT NOT NULL DEFAULT 0,
ADD COLUMN transmission VARCHAR(50) NOT NULL,
ADD COLUMN fuel_type VARCHAR(50) NOT NULL,
ADD COLUMN category VARCHAR(50) NOT NULL,
ADD COLUMN color VARCHAR(30) NOT NULL,
ADD COLUMN stock INT NOT NULL DEFAULT 1,
ADD COLUMN description TEXT,
ADD COLUMN image_url TEXT;
