server:
  port: 8080

spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: greeting-service
          uri: lb://GREETING-SERVICE
          predicates:
            - Path=/greeting,/greeting/**

        - id: currency-service
          uri: lb://CURRENCY-SERVICE
          predicates:
            - Path=/convert,/convert/**

        - id: product-service-public
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products,/products/**

        - id: product-service-admin
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/ws/product,/ws/product/**
          filters:
            - JwtAuthenticationFilter

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/ws/orders,/ws/orders/**
          filters:
            - JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:minha_chave_secreta_muito_segura_e_longa_para_o_jwt_jlpg_motors}
