server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        # Rota de Autenticação (LIVRE, não precisa de Token para logar/cadastrar!)
        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1

        # Rota de Veículos (PROTEGIDA pelo nosso Filtro JWT!)
        - id: vehicle-service-route
          uri: lb://VEHICLE-SERVICE
          predicates:
            - Path=/vehicle-service/**
          filters:
            - StripPrefix=1
            - JwtAuthenticationFilter # Aplica a validação que acabamos de programar!

        # Rota de Interações do Cliente (PROTEGIDA pelo Filtro JWT!)
        - id: customer-service-route
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer-service/**
          filters:
            - JwtAuthenticationFilter # Garante que o ID do usuário seja extraído do Token!

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/