server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:git}
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI:file:..}
          search-paths: ${CONFIG_REPO_SEARCH_PATHS:config-repo}
          default-label: ${CONFIG_REPO_LABEL:main}
          clone-on-start: false
        native:
          search-locations: ${CONFIG_NATIVE_SEARCH_LOCATIONS:file:../config-repo}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
